---

- hosts: "{{ host_name }}"
  remote_user: root
  become: true
  vars_files:
    - ~/cluster/ansible/vars/{{ cluster | default('mainnet-beta') }}.yml
    - ~/cluster/ansible/vars/main.yml
  tasks:

# Update OS packages and dependencies
  - include: ~/cluster/ansible/tasks/dependencies.yml
    tags: 
      - install_dependencies

# Set up a sol user and deploy keys
  - include: ~/cluster/ansible/tasks/user_and_keys.yml
    tags:
      - deploy_keys

# Install rust
  - include: ~/cluster/ansible/tasks/rust.yml
    when: install_rust is defined and install_rust
    tags:
      - install_rust

# Setup account on tmpfs
  - include: ~/cluster/ansible/tasks/accounts.yml
    tags:
      - setup_accounts

# Install solana cli
  - include: ~/cluster/ansible/tasks/install.yml
    tags:
      - solana_install

# Setup logs directory and log rotation
  - include: ~/cluster/ansible/tasks/logs.yml
    tags:
      - configure_logs

# Set cpu optimisations
#  - include: ~/cluster/ansible/tasks/optimizations.yml
#    tags:
#      - cpu_optimizations

# Setup identity
  - include: ~/cluster/ansible/tasks/identity.yml
    tags:
      - setup_identity

# Setup service files
  - include: ~/cluster/ansible/tasks/service.yml
    tags:
      - solana_service

# Tuning parameter
  - include: ~/cluster/ansible/tasks/tuning.yml
    tags:
      - solana_tuning

# Firewall rules
  - include: ~/cluster/ansible/tasks/firewall.yml
    tags:
      - setup_firewall

# Update scripts
  - include: tasks/update_scripts.yml
    tags:
      - update_scripts
